
transformer_cfgs:
  window_size: 8
  B_window_size: 15
  depths: 3
  sblock_depths: 2
  num_heads: 8
  embed_dim: 256
  mlp_ratio: 2
  use_checkpoint: False
  pred_sym: True


Upsampler_cfgs:
  search_range: 2
  cost_levels: 3

Syn_cfgs:
  lr: 0.05
  batch_size: 1
  scheduler_step_size: 10
  scheduler_gamma: 0.5
  scene_pth: data/train_241/
  total_epoch: 100
  model_save_fre: 100
  model_save_pth: checkpoints/
  log_path: log/